Update regress

diff --git a/regress b/regress
--- a/regress
+++ b/regress
@@ -19,10 +19,10 @@ regress_prefix() {                                              # regression tes
     prefix="${3}"
 
     if [ ! -r "${prefix}.in" ]; then                            # input file exits with read permission ?
-          echo "cannot access input file ${prefix}.in" >&2 	
+          echo "cannot read input file ${prefix}.in" >&2 	
           exit 1
       elif [ ! -r "${prefix}.out" ]; then
-          echo "cannot access output file ${prefix}.out" >&2    # input file exits with read permission ?
+          echo "cannot read output file ${prefix}.out" >&2    # input file exits with read permission ?
           exit 1
     fi
 
